// ===========================================================================
// DATA: RUBRIK MKPK EDISI 3 (Universitas Hasanuddin)
// ===========================================================================
const COURSES = [
  {id:1,name:"Komunikasi dan Kerjasama",sksRequired:2},{id:2,name:"Manajemen Kegiatan",sksRequired:2},
  {id:3,name:"Strategi Negosiasi",sksRequired:2},{id:4,name:"Pembelajaran Aktif",sksRequired:2},
  {id:5,name:"Komunikasi Digital",sksRequired:2},{id:6,name:"Empati Sosial",sksRequired:2},
  {id:7,name:"Keberagaman Budaya",sksRequired:2},{id:8,name:"Pengembangan Masyarakat",sksRequired:2},
  {id:9,name:"Kewirausahaan Rintisan 2",sksRequired:2},{id:10,name:"Kewirausahaan Rintisan 4",sksRequired:4},
  {id:11,name:"Kepemimpinan Inovatif",sksRequired:2},{id:12,name:"Pengambilan Keputusan",sksRequired:2},
  {id:13,name:"Pemecahan Masalah",sksRequired:2},{id:14,name:"Etika Profesi",sksRequired:2},
  {id:15,name:"Berfikir Kritis dan Kreatif",sksRequired:2},{id:16,name:"Kreativitas Solutif",sksRequired:2},
  {id:17,name:"Inovasi dan Pemikiran Desain",sksRequired:2},{id:18,name:"Pengembangan Talenta 1",sksRequired:1},
  {id:19,name:"Pengembangan Talenta 2",sksRequired:2},{id:20,name:"Literasi dan Presentasi Ilmiah",sksRequired:2},
  {id:21,name:"Magang atau Praktek Kerja 2",sksRequired:2},{id:22,name:"Magang atau Praktek Kerja 3",sksRequired:3},
  {id:23,name:"Magang atau Praktek Kerja 4",sksRequired:4},{id:24,name:"Magang atau Praktek Kerja 6",sksRequired:6},
  {id:25,name:"Magang atau Praktek Kerja 9",sksRequired:9},{id:26,name:"Studi atau Proyek Independen 2",sksRequired:2},
  {id:27,name:"Studi atau Proyek Independen 4",sksRequired:4},{id:28,name:"Studi atau Proyek Independen 6",sksRequired:6},
];
const courseById = (id) => COURSES.find(c => c.id === id);

const TEAM_ROLE = { label:"Peran dalam tim", key:"peran", options:[{label:"Ketua tim",value:1},{label:"Anggota tim (80%)",value:0.8}] };
const NILAI_LEMBAGA_95 = [{label:"Penyelenggara minimal setingkat BEM Universitas",value:100},{label:"Penyelenggara minimal setingkat BEM Fakultas",value:95}];
const NILAI_LEMBAGA_90 = [{label:"Penyelenggara minimal setingkat BEM Universitas",value:100},{label:"Penyelenggara minimal setingkat BEM Fakultas",value:90}];
const NILAI_DOKUMEN_90 = [{label:"Dokumen lengkap (laporan + sertifikat + surat keterangan)",value:100},{label:"Dokumen sebagian (laporan + surat keterangan saja)",value:90}];
const NILAI_KOMPETISI_GENERIK = [{label:"Juara 1, 2, atau 3 tingkat nasional",value:100},{label:"Juara Harapan",value:95},{label:"Finalis atau lolos seleksi tingkat wilayah-regional",value:90},{label:"Lolos seleksi internal (submit proposal)",value:90}];
const NILAI_TAHAPAN_MAGANG_SI = [
  {label:"Tahapan Penjajakan",weight:0.10,options:[{label:"Dokumen lengkap",value:100},{label:"Dokumen tidak lengkap",value:50}]},
  {label:"Tahapan Persiapan",weight:0.10,options:[{label:"Laporan lengkap",value:100},{label:"Laporan kurang lengkap",value:70},{label:"Laporan tidak lengkap",value:40}]},
  {label:"Tahapan Pelaksanaan",weight:0.70,options:[{label:"Laporan dan logbook lengkap",value:100},{label:"Laporan lengkap, logbook tidak lengkap",value:70},{label:"Laporan dan logbook tidak lengkap",value:40}]},
  {label:"Tahapan Evaluasi",weight:0.10,options:[{label:"Laporan lengkap",value:100},{label:"Laporan kurang lengkap",value:70},{label:"Laporan tidak lengkap",value:40}]},
];

const DATA = [
  // ================= KOMPETISI =================
  {cat:"Kompetisi",name:"Olimpiade Nasional MIPA (ONMIPA)",base:3.09,syarat:"Lolos ke Tahap Nasional",tambahanMax:8,
    tambahanOptions:[
      {label:"Memperoleh Honorable Mention tingkat nasional",value:2,group:"nasional",nilaiSync:95},{label:"Memperoleh medali emas, perak, atau perunggu tingkat nasional",value:3,group:"nasional",nilaiSync:100},
      {label:"Mewakili Universitas ke ajang Internasional (khusus bidang matematika, IMC)",value:2},{label:"Memperoleh penghargaan di ajang Internasional (khusus bidang matematika, IMC)",value:3,nilaiSync:100},
    ],
    mkpk:[4,12,13,15,16,20],nilai:NILAI_KOMPETISI_GENERIK,docs:"Logbook & dokumentasi tiap tahap seleksi, sertifikat atau SK capaian."},
  {cat:"Kompetisi",name:"NUDC & KDMI",base:3.29,syarat:"Lolos ke Tahap Nasional",tambahanMax:3,
    tambahanOptions:[{label:"Memperoleh medali pada kategori terbuka",value:2},{label:"Memperoleh medali pada kategori pemula",value:1}],
    mkpk:[1,3,4,11,12,13,16,17],
    nilai:[{label:"Juara 1, 2, atau 3",value:100},{label:"Pembicara Terbaik",value:95}],
    docs:"Logbook, dokumentasi, sertifikat atau SK capaian."},
  {cat:"Kompetisi",name:"PILMAPRES",base:4.76,syarat:"Lolos ke Tahap Nasional",tambahanMax:3,
    tambahanOptions:[
      {label:"Menjadi juara tingkat Universitas",value:0.25},{label:"Menjadi wakil tingkat Wilayah",value:0.5},
      {label:"Juara 1, 2, atau 3 tingkat Nasional",value:2,group:"nasional",nilaiSync:100},{label:"Juara Harapan",value:1,group:"nasional",nilaiSync:95},{label:"Honorable Mention",value:1,group:"nasional",nilaiSync:90},
    ],
    mkpk:[4,5,11,13,15,16,17,18,19,20],
    nilai:[{label:"Juara 1, 2, atau 3 tingkat Nasional",value:100},{label:"Juara Harapan",value:95},{label:"Honorable Mention, Finalis, atau Lolos Seleksi tingkat Wilayah-Regional",value:90}],
    docs:"Logbook, portofolio, sertifikat atau SK capaian."},
  {cat:"Kompetisi",name:"PKM – PIMNAS",base:6.32,syarat:"Lolos Pendanaan",tambahanMax:4,
    tambahanOptions:[{label:"Menjadi mahasiswa bertalenta",value:1},{label:"Medali Presentasi",value:2,nilaiSync:100},{label:"Medali Poster",value:1,nilaiSync:100}],
    tahapanLanjut:{label:"Melaksanakan tahap PIMNAS (tahapan lanjut)",value:3.78},
    coeff:[TEAM_ROLE],mkpk:[1,2,3,5,8,9,10,12,13,15,16,18,19,20],
    nilai:[{label:"Memperoleh medali emas, perak, atau perunggu",value:100},{label:"Mengikuti setiap kegiatan sebelum PIMNAS",value:95}],
    docs:"Proposal & bukti submit, logbook, laporan kemajuan, dokumentasi karya, sertifikat atau SK."},
  {cat:"Kompetisi",name:"Kontes Robot Indonesia (KRI)",base:4.2,syarat:"Lolos ke Tingkat Wilayah",tambahanMax:7,
    tambahanOptions:[{label:"Juara 1, 2, atau 3 tingkat Nasional",value:2,group:"nasional",nilaiSync:100},{label:"Juara Harapan",value:1,group:"nasional",nilaiSync:95},{label:"Mewakili Universitas ke ajang Internasional",value:2},{label:"Memperoleh penghargaan di ajang Internasional",value:3,nilaiSync:100}],
    tahapanLanjut:{label:"Lolos hingga Tingkat Nasional (tahapan lanjut)",value:1.31},
    coeff:[TEAM_ROLE],mkpk:[1,5,13,15,16,17,20],nilai:NILAI_KOMPETISI_GENERIK,docs:"Logbook, proposal & bukti submit, dokumentasi karya, sertifikat atau SK."},
  {cat:"Kompetisi",name:"Kontes Mobil Hemat Energi (KMHE)",base:4.53,syarat:"Lolos ke Tingkat Wilayah",tambahanMax:7,
    tambahanOptions:[{label:"Juara 1, 2, atau 3 tingkat Nasional",value:2,group:"nasional",nilaiSync:100},{label:"Juara Harapan",value:1,group:"nasional",nilaiSync:95},{label:"Mewakili Universitas ke ajang Internasional",value:2},{label:"Memperoleh penghargaan di ajang Internasional",value:3,nilaiSync:100}],
    tahapanLanjut:{label:"Lolos hingga Tingkat Nasional (tahapan lanjut)",value:1.47},
    coeff:[TEAM_ROLE],mkpk:[1,5,13,15,16,17,20],nilai:NILAI_KOMPETISI_GENERIK,docs:"Logbook, proposal, dokumentasi karya, sertifikat atau SK."},
  {cat:"Kompetisi",name:"Kontes Kapal Indonesia (KKI)",base:3.42,syarat:"Lolos ke Tingkat Wilayah",tambahanMax:7,
    tambahanOptions:[{label:"Juara 1, 2, atau 3 tingkat Nasional",value:2,group:"nasional",nilaiSync:100},{label:"Juara Harapan",value:1,group:"nasional",nilaiSync:95},{label:"Mewakili Universitas ke ajang Internasional",value:2},{label:"Memperoleh penghargaan di ajang Internasional",value:3,nilaiSync:100}],
    tahapanLanjut:{label:"Lolos hingga Tingkat Nasional (tahapan lanjut)",value:2.58},
    coeff:[TEAM_ROLE],mkpk:[1,5,13,15,16,17,20],nilai:NILAI_KOMPETISI_GENERIK,docs:"Logbook, proposal, dokumentasi karya, sertifikat atau SK."},
  {cat:"Kompetisi",name:"Kompetisi Jembatan Indonesia (KJI)",base:5.58,syarat:"Lolos ke Tingkat Nasional",tambahanMax:3,
    tambahanOptions:[{label:"Juara 1, 2, atau 3 tingkat Nasional",value:2,group:"nasional",nilaiSync:100},{label:"Juara Harapan",value:1,group:"nasional",nilaiSync:95},{label:"Juara Kategori",value:1,nilaiSync:95}],
    coeff:[TEAM_ROLE],mkpk:[1,5,13,15,16,17,20],
    nilai:[{label:"Juara 1, 2, atau 3",value:100},{label:"Juara Kategori atau Harapan",value:95}],
    docs:"Logbook, proposal & bukti submit, dokumentasi karya, sertifikat atau SK."},
  {cat:"Kompetisi",name:"Kompetisi Bangunan Gedung Indonesia (KBGI)",base:5.58,syarat:"Lolos ke Tingkat Nasional",tambahanMax:3,
    tambahanOptions:[{label:"Juara 1, 2, atau 3 tingkat Nasional",value:2,group:"nasional",nilaiSync:100},{label:"Juara Harapan",value:1,group:"nasional",nilaiSync:95},{label:"Juara Kategori",value:1,nilaiSync:95}],
    coeff:[TEAM_ROLE],mkpk:[1,5,13,15,16,17,20],
    nilai:[{label:"Juara 1, 2, atau 3",value:100},{label:"Juara Kategori atau Harapan",value:95}],
    docs:"Logbook, proposal, dokumentasi karya, sertifikat atau SK."},
  {cat:"Kompetisi",name:"Kontes Robot Terbang Indonesia (KRTI)",base:5.11,syarat:"Lolos ke Tingkat Wilayah",tambahanMax:7,
    tambahanOptions:[{label:"Juara 1, 2, atau 3 tingkat Nasional",value:2,group:"nasional",nilaiSync:100},{label:"Juara Harapan",value:1,group:"nasional",nilaiSync:95},{label:"Mewakili Universitas ke ajang Internasional",value:2},{label:"Memperoleh penghargaan di ajang Internasional",value:3,nilaiSync:100}],
    tahapanLanjut:{label:"Lolos hingga Tingkat Nasional (tahapan lanjut)",value:0.89},
    coeff:[TEAM_ROLE],mkpk:[1,5,13,15,16,17,20],nilai:NILAI_KOMPETISI_GENERIK,docs:"Logbook, proposal, dokumentasi karya, sertifikat atau SK."},
  {cat:"Kompetisi",name:"Lomba Inovasi Digital Mahasiswa (LIDM)",base:3.4,syarat:"Lolos ke Tingkat Nasional",desc:"Kompetisi Kemendikbud di bidang inovasi digital untuk pendidikan atau pembelajaran.",tambahanMax:1,
    tambahanOptions:[{label:"Juara 1, 2, atau 3",value:1}],
    mkpk:[1,4,5,15,16,17],docs:"Logbook, proposal atau karya, sertifikat atau SK."},
  {cat:"Kompetisi",name:"Satria Data – NSC",base:4.0,syarat:"Lolos ke Tingkat Nasional",desc:"Kompetisi statistika nasional oleh BPS, kategori analisis statistik umum (National Statistics Competition).",tambahanMax:2,tambahanOptions:[{label:"Memperoleh penghargaan khusus tingkat nasional",value:1,group:"nasional",nilaiSync:95},{label:"Memperoleh medali emas, perak, atau perunggu tingkat nasional",value:2,group:"nasional",nilaiSync:100}],mkpk:[1,4,5,12,13,16,17,20],nilai:NILAI_KOMPETISI_GENERIK,docs:"Logbook, karya, sertifikat atau SK."},
  {cat:"Kompetisi",name:"Satria Data – SEC",base:2.61,syarat:"Lolos ke Tingkat Nasional",desc:"Kompetisi statistika BPS, kategori penulisan esai berbasis data (Statistics Essay Competition).",tambahanMax:2,tambahanOptions:[{label:"Memperoleh penghargaan khusus tingkat nasional",value:1,group:"nasional",nilaiSync:95},{label:"Memperoleh medali emas, perak, atau perunggu tingkat nasional",value:2,group:"nasional",nilaiSync:100}],mkpk:[1,4,5,12,13,16,17,20],nilai:NILAI_KOMPETISI_GENERIK,docs:"Logbook, karya, sertifikat atau SK."},
  {cat:"Kompetisi",name:"Satria Data – SIC",base:2.61,syarat:"Lolos ke Tingkat Nasional",desc:"Kompetisi statistika BPS, kategori infografis data (Statistics Infographic Competition).",tambahanMax:2,tambahanOptions:[{label:"Memperoleh penghargaan khusus tingkat nasional",value:1,group:"nasional",nilaiSync:95},{label:"Memperoleh medali emas, perak, atau perunggu tingkat nasional",value:2,group:"nasional",nilaiSync:100}],mkpk:[1,4,5,12,13,16,17,20],nilai:NILAI_KOMPETISI_GENERIK,docs:"Logbook, karya, sertifikat atau SK."},
  {cat:"Kompetisi",name:"Satria Data – BDC",base:3.83,syarat:"Lolos ke Tingkat Nasional",desc:"Kompetisi statistika BPS, kategori pengolahan big data (Big Data Challenge).",tambahanMax:2,tambahanOptions:[{label:"Memperoleh penghargaan khusus tingkat nasional",value:1,group:"nasional",nilaiSync:95},{label:"Memperoleh medali emas, perak, atau perunggu tingkat nasional",value:2,group:"nasional",nilaiSync:100}],mkpk:[1,4,5,12,13,16,17,20],nilai:NILAI_KOMPETISI_GENERIK,docs:"Logbook, karya, sertifikat atau SK."},
  {cat:"Kompetisi",name:"PPK Ormawa – Tim Pelaksana",base:6.93,syarat:"Lolos pendanaan & selesai kegiatan",desc:"Program Penguatan Kapasitas Ormawa, yaitu pendanaan Kemendikbud untuk organisasi mahasiswa menjalankan proyek pemberdayaan masyarakat.",tambahanMax:2,
    tambahanOptions:[{label:"Penghargaan Abdidaya Terbaik 1, 2, 3, atau 4 kategori Tim Pelaksana",value:2,nilaiSync:100}],
    tahapanLanjut:{label:"Lolos hingga Abdidaya (tahapan lanjut)",value:3.69},
    mkpk:[1,2,3,5,6,8,9,10,12,13,16,18,19,20],nilai:NILAI_KOMPETISI_GENERIK,docs:"Proposal, laporan kemajuan, laporan akhir, dokumentasi, SK."},
  {cat:"Kompetisi",name:"PPK Ormawa – Perwakilan Ormawa",base:1.6,syarat:"Lolos pendanaan & selesai kegiatan",desc:"Anggota ormawa yang ditugaskan mewakili organisasi dalam program PPK Ormawa, bukan bagian tim pelaksana inti.",tambahanMax:5,
    tambahanOptions:[{label:"Penghargaan Abdidaya Terbaik 1, 2, 3, atau 4 kategori Ormawa",value:2,nilaiSync:100}],
    tahapanLanjut:{label:"Lolos hingga Abdidaya (tahapan lanjut)",value:0.54},
    tambahanNote:"Maksimal tambahan di rubrik untuk peran ini adalah 5.00 SKS, tapi baru 2 opsi di atas yang datanya terkonfirmasi. Sisanya kemungkinan besar bonus dari peran Kepengurusan (Ketua/pengurus ormawa yang mengkoordinir PPK Ormawa), diklaim melalui MKPK Kepengurusan secara terpisah, bukan melalui peran Perwakilan ini.",
    mkpk:[1,2,3,5,6,8,9,10,12,13,16,18,19,20],nilai:NILAI_KOMPETISI_GENERIK,docs:"SK penugasan, logbook, dokumentasi."},
  {cat:"Kompetisi",name:"PPK Ormawa – Pendanaan Internal",base:6.4,syarat:"Dapat pendanaan internal & selesai kegiatan",desc:"PPK Ormawa yang didanai internal kampus (bukan lolos pendanaan Kemendikbud).",tambahanMax:0,mkpk:[1,2,3,5,6,8,9,10,12,13,16,18,19,20],nilai:NILAI_KOMPETISI_GENERIK,docs:"SK pendanaan, laporan, dokumentasi."},
  {cat:"Kompetisi",name:"Musabaqah Tilawatil Qur'an (MTQ)",base:1.0,syarat:"Juara 1–3 Provinsi atau Nasional atau lolos Tahap Nasional",desc:"Lomba tilawah, hafalan, atau pemahaman Al-Qur'an tingkat provinsi hingga nasional.",tambahanMax:5.75,
    coeff:[{label:"Tingkat kompetisi",key:"tingkat",options:[{label:"MTQ Internasional",value:3},{label:"MTQ Nasional",value:2.5},{label:"MTQM Nasional",value:2},{label:"MTQ Provinsi",value:1.5},{label:"MTQM Unhas",value:1}]}],
    tambahanOptions:[{label:"Juara 1, 2, atau 3 MTQM tingkat Unhas",value:0.5},{label:"Juara 1, 2, atau 3 MTQ tingkat Provinsi",value:0.75},{label:"Juara 1, 2, atau 3 MTQM tingkat Nasional",value:1},{label:"Juara 1, 2, atau 3 MTQ tingkat Nasional",value:1.5},{label:"Juara 1, 2, atau 3 MTQ tingkat Internasional",value:2}],mkpk:[1,15,16,18,19,20],nilai:NILAI_KOMPETISI_GENERIK,docs:"Sertifikat atau SK, dokumentasi."},
  {cat:"Kompetisi",name:"GEMASTIK Bidang I & II",base:3.15,syarat:"Lolos ke Tingkat Nasional",tambahanMax:1.5,tambahanOptions:[{label:"Memperoleh penghargaan khusus tingkat nasional",value:0.5,nilaiSync:95},{label:"Memperoleh medali emas, perak, atau perunggu tingkat nasional",value:1,nilaiSync:100}],mkpk:[1,4,5,12,13,14,15,16,17,20],nilai:NILAI_KOMPETISI_GENERIK,docs:"Logbook, karya, sertifikat atau SK."},
  {cat:"Kompetisi",name:"GEMASTIK Bidang III, IV, V, VI, VII, X, XI",base:3.15,syarat:"Lolos ke Tingkat Nasional",tambahanMax:3,
    tambahanOptions:[{label:"Memperoleh penghargaan khusus tingkat nasional",value:1,nilaiSync:95},{label:"Memperoleh medali emas, perak, atau perunggu tingkat nasional",value:2,nilaiSync:100}],
    mkpk:[1,4,5,12,13,14,15,16,17,20],nilai:NILAI_KOMPETISI_GENERIK,docs:"Logbook, karya, sertifikat atau SK."},
  {cat:"Kompetisi",name:"GEMASTIK Bidang VIII & IX",base:3.15,syarat:"Lolos ke Tingkat Nasional",tambahanMax:5,
    tambahanOptions:[{label:"Memperoleh penghargaan khusus tingkat nasional",value:2,nilaiSync:95},{label:"Memperoleh medali emas, perak, atau perunggu tingkat nasional",value:3,nilaiSync:100}],
    mkpk:[1,4,5,12,13,14,15,16,17,20],nilai:NILAI_KOMPETISI_GENERIK,docs:"Logbook, karya, sertifikat atau SK."},
  {cat:"Kompetisi",name:"KBMK (Bisnis, Manajemen, Keuangan)",base:3.0,syarat:"Lolos ke Babak Final",desc:"Kompetisi Mahasiswa Nasional Bidang Ilmu Bisnis, Manajemen, dan Keuangan.",tambahanMax:1,tambahanOptions:[{label:"Memperoleh penghargaan terbaik 1, 2, atau 3",value:1,nilaiSync:100}],mkpk:[1,9,10,16,17],
    nilai:[{label:"Juara 1, 2, atau 3",value:100},{label:"Pelaksanaan Babak Grand Final",value:95},{label:"Pelaksanaan Babak Semi Final",value:90}],
    docs:"Logbook, karya, sertifikat atau SK."},
  {cat:"Kompetisi",name:"Kompetisi Kemaritiman Mahasiswa Nasional (KKMN)",base:2.02,syarat:"Lolos sebagai Finalis",desc:"Kompetisi nasional bertema kemaritiman (kelautan, perikanan, kepelabuhan, dll.).",tambahanMax:1.5,tambahanOptions:[{label:"Juara 1, 2, atau 3 kategori Presentasi",value:1},{label:"Juara 1, 2, atau 3 kategori Poster",value:0.5}],mkpk:[1,16],docs:"Logbook, karya, sertifikat atau SK."},
  {cat:"Kompetisi",name:"PORPROV, POMNAS, PON, atau Lomba Olahraga Regional-Internasional",base:1.93,syarat:"Memenangkan lomba",tambahanMax:0,
    coeff:[{label:"Tingkat kompetisi",key:"tingkat",options:[{label:"Olimpiade",value:10},{label:"ASIAN Games",value:5},{label:"SEA Games",value:4},{label:"PON atau lomba tingkat Internasional",value:3},{label:"POMNAS atau lomba mahasiswa tingkat Nasional",value:2},{label:"PORPROV atau lomba tingkat Provinsi",value:1}]}],
    mkpk:[1,3,4,7,11,12,13,14,18,19],
    nilai:[{label:"Juara 1, 2, atau 3",value:100},{label:"Juara Harapan",value:90},{label:"Finalis",value:85}],
    docs:"Sertifikat atau SK, dokumentasi."},
  {cat:"Kompetisi",name:"PEKSIMINAS atau PEKSIMIDA",base:1.73,syarat:"Lolos ke Tingkat Nasional",tambahanMax:1,tambahanOptions:[{label:"Memperoleh juara pada PEKSIMINAS",value:1,nilaiSync:100}],mkpk:[1,7,18,19],
    nilai:[{label:"Juara 1, 2, atau 3 tingkat Nasional",value:100},{label:"Mengikuti PEKSIMINAS (lomba tingkat nasional)",value:95},{label:"Mengikuti PEKSIMIDA (lomba tingkat daerah)",value:90},{label:"Lolos seleksi tingkat Universitas",value:85}],
    docs:"Sertifikat atau SK, dokumentasi."},
  {cat:"Kompetisi",name:"Lomba Paduan Suara Mahasiswa (LPSM)",base:1.38,syarat:"Lolos ke Tingkat Nasional",tambahanMax:1,
    tambahanOptions:[{label:"Juara pada tingkat Nasional",value:1,nilaiSync:100}],
    mkpk:[1,18,19],
    nilai:[{label:"Juara 1, 2, 3, atau Juara Harapan 1-2",value:100},{label:"Mengikuti Lomba Nasional",value:95},{label:"Mengikuti Seleksi Penyisihan",value:90},{label:"Lolos Seleksi Penyisihan",value:85}],
    docs:"Sertifikat atau SK, dokumentasi."},
  {cat:"Kompetisi",name:"Pesta Paduan Suara Gerejawi (PESPARAWI)",base:0.85,syarat:"Lolos ke Tingkat Nasional",tambahanMax:1,
    tambahanOptions:[{label:"Juara pada tingkat Nasional",value:1,nilaiSync:100}],
    mkpk:[1,18,19],
    nilai:[{label:"Juara 1, 2, atau 3",value:100},{label:"Juara Harapan 1 atau 2",value:95},{label:"Lolos Seleksi Penyisihan (mengikuti lomba nasional)",value:90}],
    docs:"Sertifikat atau SK, dokumentasi."},
  {cat:"Kompetisi",name:"Juri atau Wasit Penalaran, Seni, Olahraga",base:1.0,syarat:"Sertifikat atau SK dari pejabat berwenang",tambahanMax:0,
    coeff:[{label:"Cakupan penugasan",key:"cakupan",options:[{label:"Internasional (tercatat di Belmawa)",value:2},{label:"Nasional Belmawa atau Internasional",value:1.5},{label:"Nasional Non-Belmawa",value:1},{label:"Provinsi",value:0.5}]}],
    mkpk:[12,14],docs:"Sertifikat atau SK dari pejabat berwenang, dokumentasi saat bertugas."},
  {cat:"Kompetisi",name:"Lomba Mandiri Bidang Penalaran",base:0.58,syarat:"Memenangkan lomba",tambahanMax:0,
    coeff:[{label:"Skala penyelenggara",key:"skala",options:[{label:"Kompetisi Internasional bereputasi",value:2.5},{label:"Setingkat institusi (luring) atau Internasional (daring)",value:2},{label:"Setingkat BEM Universitas, Fakultas atau Himpunan, Departemen atau Prodi, atau UKM Universitas (luring)",value:1.5},{label:"Diselenggarakan secara daring",value:1}]}],
    mkpk:[4,13,20],
    nilai:[{label:"Juara 1, 2, atau 3",value:100},{label:"Juara Harapan",value:90}],
    docs:"Sertifikat atau SK, dokumentasi."},
  {cat:"Kompetisi",name:"Lomba Mandiri Bidang Seni & Olahraga",base:0.56,syarat:"Memenangkan lomba",tambahanMax:0,
    coeff:[{label:"Skala penyelenggara",key:"skala",options:[{label:"Kompetisi Internasional bereputasi",value:2.5},{label:"Setingkat institusi (luring) atau Internasional (daring)",value:2},{label:"Setingkat BEM Universitas, Fakultas atau Himpunan, Departemen atau Prodi, atau UKM Universitas (luring)",value:1.5},{label:"Diselenggarakan secara daring",value:1}]}],
    mkpk:[4,18,19],
    nilai:[{label:"Juara 1, 2, atau 3",value:100},{label:"Juara Harapan",value:90}],
    docs:"Sertifikat atau SK, dokumentasi."},
  {cat:"Kompetisi",name:"Unhas Freshmen Talent Competition (UFTC)",base:0.8,syarat:"Lolos Babak Final sebagai Finalis",tambahanMax:0.5,
    tambahanOptions:[{label:"Meraih juara 1, 2, atau 3",value:0.5}],
    mkpk:[18,19],docs:"Sertifikat atau SK, dokumentasi."},
  {cat:"Kompetisi",name:"Pentas Seni (PENSI)",base:0.8,syarat:"Lolos Babak Final sebagai Finalis",tambahanMax:0.5,
    tambahanOptions:[{label:"Meraih juara 1, 2, atau 3",value:0.5}],
    mkpk:[18,19],docs:"Sertifikat atau SK, dokumentasi."},

  // ================= KEWIRAUSAHAAN =================
  {cat:"Kewirausahaan",name:"Program Mahasiswa Wirausaha (PMW)",base:3.18,syarat:"Lolos pendanaan & selesai kegiatan",desc:"Program pendanaan usaha rintisan dari kampus (internal Universitas Hasanuddin).",tambahanMax:1,
    tambahanOptions:[{label:"Menjadi wirausaha pemula berkelanjutan (tahap bertumbuh)",value:1},{label:"Mendapatkan penghargaan 1, 2, atau 3",value:0.5}],
    coeff:[TEAM_ROLE],mkpk:[1,2,3,4,9,10],docs:"Proposal ide & usaha, BMC, laporan bulanan usaha, laporan kemajuan, laporan akhir & sertifikat."},
  {cat:"Kewirausahaan",name:"Program Pembinaan Mahasiswa Wirausaha (P2MW)",base:4.18,syarat:"Lolos pendanaan & selesai kegiatan dengan baik",desc:"Program pendanaan wirausaha dari Kemendikbud (Belmawa), jenjang lebih tinggi dari PMW, bermuara ke KMI Award.",tambahanMax:1,tambahanOptions:[{label:"Mendapatkan penghargaan KMI Award",value:1,nilaiSync:100}],
    tahapanLanjut:{label:"Menjadi Finalis KMI Award (tahapan lanjut)",value:2},
    coeff:[TEAM_ROLE],mkpk:[1,2,3,4,5,9,10,12,13],
    nilai:[{label:"Juara 1, 2, atau 3 KMI Award",value:100},{label:"Juara Harapan KMI Award",value:95},{label:"Finalis KMI Award",value:90},{label:"Lolos pendanaan dan melaksanakan usaha",value:85}],
    docs:"Proposal, laporan kemajuan, laporan akhir, dokumen KMI Award (jika ada)."},
  {cat:"Kewirausahaan",name:"Wirausaha Mandiri",base:2.08,syarat:"Usia usaha minimal 3 bulan, margin keuntungan minimal 15%, dan memiliki dokumen kelengkapan usaha minimal NIB",desc:"Usaha pribadi yang berjalan tanpa pendanaan program kampus (modal sendiri).",tambahanMax:0,mkpk:[2,9,10],
    nilai:[{label:"Usia usaha lebih dari 6 bulan",value:100},{label:"Usia usaha 3-6 bulan",value:95}],
    docs:"Dokumen kelengkapan usaha minimal NIB, bukti cashflow atau margin keuntungan."},

  // ================= KEORGANISASIAN =================
  {cat:"Keorganisasian",name:"Kepengurusan",base:3.05,syarat:"Menyelesaikan tugas kepengurusan 1 periode penuh",tambahanMax:7,
    tambahanOptions:[
      {label:"Tim PPK Ormawa lolos seleksi presentasi proposal Belmawa",value:0.5},{label:"Tim PPK Ormawa lolos pendanaan",value:0.5},
      {label:"Tim PPK Ormawa lolos hingga Abdidaya",value:1},{label:"Tim Pelaksana PPK Ormawa mendapat award di Abdidaya",value:1},
      {label:"Ormawa mendapat award di Abdidaya",value:1},{label:"Ormawa jadi tuan rumah pertemuan Nasional (min. 5 provinsi, luring)",value:1},
      {label:"Ormawa jadi tuan rumah pertemuan Internasional (min. 5 negara, luring)",value:2},
    ],
    mkpk:[1,2,3,6,7,11,12,13,14,15,16],
    coeff:[
      {label:"Jabatan",key:"jabatan",options:[{label:"Ketua",value:1.5},{label:"Wakil Ketua, Sekretaris, Bendahara, atau Koordinator Bidang",value:1},{label:"Anggota",value:0.5}]},
      {label:"Cakupan organisasi",key:"cakupan",options:[{label:"Internasional",value:2},{label:"Nasional atau BEM Universitas",value:1.5},{label:"Provinsi-Regional atau BEM Fakultas",value:1},{label:"Himpunan Departemen atau UKM Universitas atau cabang organisasi internasional atau tingkat kabupaten",value:0.75},{label:"Lokal atau UKM Fakultas",value:0.5},{label:"Organisasi pengawas Ormawa",value:0.5}]},
    ],
    docs:"SK pembentukan organisasi atau tanda daftar, AD atau ART, Program Kerja awal periode (TTD & diketahui pimpinan), Laporan Pertanggungjawaban (LPJ) akhir periode."},
  {cat:"Keorganisasian",name:"Kepanitiaan",base:0.42,syarat:"Menyelesaikan tugas kepanitiaan",tambahanMax:0,mkpk:[1,2,3,6,7,11,12,13,14,15,16],
    coeff:[
      {label:"Jabatan",key:"jabatan",options:[{label:"Ketua",value:1.5},{label:"Wakil Ketua, Sekretaris, Bendahara, atau Koordinator Bidang",value:1},{label:"Anggota",value:0.5}]},
      {label:"Cakupan kepanitiaan",key:"cakupan",options:[{label:"Internasional (luring)",value:2},{label:"Nasional (luring) atau Internasional (daring)",value:1.5},{label:"Provinsi-Regional (luring) atau Nasional (daring)",value:1},{label:"Intra kampus",value:0.75}]},
    ],
    docs:"SK Pengangkatan panitia, laporan pelaksanaan tiap kegiatan (TTD & diketahui pimpinan), logbook & dokumentasi."},

  // ================= KEPESERTAAN =================
  {cat:"Kepesertaan",name:"Pelatihan (sebagai Peserta)",base:0.2,syarat:"Menyelesaikan pelatihan sebagai peserta",tambahanMax:0,mkpk:[18,19,20],
    coeff:[{label:"Durasi",key:"durasi",options:[{label:"> 24 jam",value:2},{label:"17–24 jam",value:1.5},{label:"9–16 jam",value:1},{label:"0–8 jam",value:0.5}]}],
    nilai:NILAI_LEMBAGA_95,docs:"Bukti pendaftaran, sertifikat kegiatan, dokumentasi."},
  {cat:"Kepesertaan",name:"Pelatihan (sebagai Fasilitator, Instruktur, atau Narasumber)",base:0.45,syarat:"Menyelesaikan pelatihan sebagai fasilitator",tambahanMax:0,mkpk:[18,19,20],
    coeff:[{label:"Durasi",key:"durasi",options:[{label:"> 24 jam",value:2},{label:"17–24 jam",value:1.5},{label:"9–16 jam",value:1},{label:"0–8 jam",value:0.5}]}],
    nilai:NILAI_LEMBAGA_95,docs:"Surat penugasan atau sertifikat, laporan, bahan presentasi, dokumentasi."},
  {cat:"Kepesertaan",name:"Sertifikasi Kompetensi",base:1.05,syarat:"Lulus ujian kompetensi",desc:"Uji kompetensi resmi oleh Lembaga Sertifikasi Profesi (LSP), beda dari sekadar sertifikat pelatihan biasa.",tambahanMax:0,mkpk:[18,19,20],docs:"Bukti pendaftaran, sertifikat kompetensi, dokumentasi."},
  {cat:"Kepesertaan",name:"Pelatihan Terprogram",base:0.27,syarat:"Menyelesaikan pelatihan terprogram (maks. 1x per tahun, min. penyelenggara setingkat fakultas)",desc:"Pelatihan berjenjang atau berkelanjutan dengan kurikulum terstruktur (bukan pelatihan satu kali seperti kategori \"Pelatihan\" biasa).",tambahanMax:0,mkpk:[4,6,7,14,20],
    coeff:[{label:"Jam pelatihan",key:"jam",options:[{label:"≥ 90 jam",value:8},{label:"51–90 jam",value:6},{label:"26–50 jam",value:4},{label:"13–25 jam",value:2},{label:"≤ 12 jam",value:1}]}],
    nilai:NILAI_LEMBAGA_90,docs:"Bukti pendaftaran, sertifikat kegiatan & logbook, laporan tugas."},
  {cat:"Kepesertaan",name:"Lokakarya (sebagai Peserta)",base:0.2,syarat:"Menyelesaikan lokakarya sebagai peserta",tambahanMax:0,mkpk:[18,19],
    coeff:[{label:"Durasi",key:"durasi",options:[{label:"> 24 jam",value:2},{label:"17–24 jam",value:1.5},{label:"9–16 jam",value:1},{label:"0–8 jam",value:0.5}]}],
    nilai:NILAI_LEMBAGA_90,docs:"Bukti pendaftaran, sertifikat kegiatan, dokumentasi."},
  {cat:"Kepesertaan",name:"Lokakarya (sebagai Narasumber atau Fasilitator)",base:0.44,syarat:"Menyelesaikan lokakarya sebagai narasumber",tambahanMax:0,mkpk:[18,19],
    coeff:[{label:"Durasi",key:"durasi",options:[{label:"> 24 jam",value:2},{label:"17–24 jam",value:1.5},{label:"9–16 jam",value:1},{label:"0–8 jam",value:0.5}]}],
    nilai:NILAI_LEMBAGA_90,docs:"Surat penugasan atau sertifikat, laporan, bahan presentasi, dokumentasi."},
  {cat:"Kepesertaan",name:"Seminar (sebagai Peserta)",base:0.07,syarat:"Menyelesaikan seminar sebagai peserta",tambahanMax:0,mkpk:[4,20],
    coeff:[{label:"Skala kegiatan",key:"skala",options:[{label:"Internasional atau Regional",value:3},{label:"Nasional (>5 provinsi)",value:2},{label:"Wilayah, Provinsi, atau Dalam PT",value:1}]}],
    nilai:NILAI_LEMBAGA_90,docs:"Bukti pendaftaran, sertifikat kegiatan, dokumentasi."},
  {cat:"Kepesertaan",name:"Seminar (sebagai Narasumber atau Presenter)",base:0.4,syarat:"Menyelesaikan seminar sebagai narasumber",tambahanMax:0,mkpk:[4,20],
    coeff:[{label:"Skala kegiatan",key:"skala",options:[{label:"Internasional atau Regional",value:3},{label:"Nasional (>5 provinsi)",value:2},{label:"Wilayah, Provinsi, atau Dalam PT",value:1}]}],
    nilai:NILAI_LEMBAGA_90,docs:"Surat penugasan atau sertifikat, laporan, bahan presentasi, dokumentasi."},
  {cat:"Kepesertaan",name:"Konferensi Ilmiah (sebagai Peserta)",base:0.06,syarat:"Menyelesaikan konferensi ilmiah sebagai peserta",tambahanMax:0,mkpk:[4,20],
    coeff:[{label:"Skala kegiatan",key:"skala",options:[{label:"Internasional atau Regional",value:3},{label:"Nasional (>5 provinsi)",value:2},{label:"Wilayah, Provinsi, atau Dalam PT",value:1}]}],
    nilai:NILAI_LEMBAGA_90,docs:"Bukti pendaftaran, sertifikat, dokumentasi."},
  {cat:"Kepesertaan",name:"Konferensi Ilmiah (sebagai Narasumber atau Presenter)",base:0.4,syarat:"Menyelesaikan konferensi ilmiah sebagai narasumber",tambahanMax:0,mkpk:[4,20],
    coeff:[{label:"Skala kegiatan",key:"skala",options:[{label:"Internasional atau Regional",value:3},{label:"Nasional (>5 provinsi)",value:2},{label:"Wilayah, Provinsi, atau Dalam PT",value:1}]}],
    nilai:NILAI_LEMBAGA_90,docs:"Surat penugasan atau sertifikat, laporan, bahan presentasi, dokumentasi."},
  {cat:"Kepesertaan",name:"Kuliah Umum (sebagai Peserta)",base:0.06,syarat:"Menyelesaikan kuliah umum sebagai peserta",tambahanMax:0,mkpk:[4,20],
    coeff:[{label:"Skala kegiatan",key:"skala",options:[{label:"Internasional atau Regional",value:3},{label:"Nasional (>5 provinsi)",value:2},{label:"Wilayah, Provinsi, atau Dalam PT",value:1}]}],
    nilai:NILAI_LEMBAGA_90,docs:"Bukti pendaftaran, sertifikat, dokumentasi."},
  {cat:"Kepesertaan",name:"Kuliah Umum (sebagai Narasumber atau Presenter)",base:0.4,syarat:"Menyelesaikan kuliah umum sebagai narasumber",tambahanMax:0,mkpk:[4,20],
    coeff:[{label:"Skala kegiatan",key:"skala",options:[{label:"Internasional atau Regional",value:3},{label:"Nasional (>5 provinsi)",value:2},{label:"Wilayah, Provinsi, atau Dalam PT",value:1}]}],
    nilai:NILAI_LEMBAGA_90,docs:"Surat penugasan atau sertifikat, laporan, bahan presentasi, dokumentasi."},
  {cat:"Kepesertaan",name:"Kredensial Mikro",base:0.23,syarat:"Menyelesaikan course & memperoleh sertifikat kelulusan",desc:"Sertifikat course singkat dari platform pembelajaran (Coursera, edX, LinkedIn Learning, dll.), bukan pelatihan formal kampus.",tambahanMax:0,mkpk:[4,5,18,19],
    coeff:[{label:"Durasi course",key:"durasi",options:[{label:"> 20 jam",value:5},{label:"16–20 jam",value:4},{label:"11–15 jam",value:3},{label:"5–10 jam",value:2}]},{label:"Bahasa pengantar course",key:"bahasa",options:[{label:"Bahasa Asing",value:1.5},{label:"Bahasa Indonesia",value:1}]}],
    docs:"Sertifikat kelulusan course."},
  {cat:"Kepesertaan",name:"Pertukaran Mahasiswa",base:1.6,syarat:"Menyelesaikan kegiatan pertukaran mahasiswa (>1 bulan)",desc:"Program resmi pertukaran atau credit transfer antar perguruan tinggi (mis. IISMA, Permata), beda dari short course biasa.",tambahanMax:0.5,tambahanOptions:[{label:"Memperoleh pendanaan atau beasiswa (termasuk enrichment program kelas internasional)",value:0.5}],mkpk:[3,4,5,7,11,12,20],
    coeff:[{label:"Skala kegiatan",key:"skala",options:[{label:"Internasional",value:2},{label:"Nasional",value:1}]},{label:"Durasi kegiatan",key:"durasi",options:[{label:"5–6 bulan",value:2},{label:"3–4 bulan",value:1.5},{label:"> 1–2 bulan",value:1}]}],
    docs:"Sertifikat, dokumentasi, laporan kegiatan."},
  {cat:"Kepesertaan",name:"Short Course",base:1.24,syarat:"Menyelesaikan short course",desc:"Program belajar singkat di institusi lain (dalam atau luar negeri) tanpa status pertukaran resmi antar kampus.",tambahanMax:0.5,tambahanOptions:[{label:"Memperoleh pendanaan atau beasiswa (termasuk enrichment program kelas internasional)",value:0.5}],mkpk:[4,5,7,11,12,20],
    coeff:[{label:"Skala kegiatan",key:"skala",options:[{label:"Internasional",value:2},{label:"Nasional",value:1}]},{label:"Durasi kegiatan",key:"durasi",options:[{label:"21–30 hari",value:2},{label:"10–20 hari",value:1.5},{label:"< 10 hari",value:1}]}],
    docs:"Sertifikat, dokumentasi, laporan kegiatan."},
  {cat:"Kepesertaan",name:"Gerakan Unhas Mengkaji & Shalat Berjamaah (GUMSB)",base:0.4,syarat:"Menyelesaikan program GUMSB",desc:"Program kajian & shalat berjamaah rutin yang diselenggarakan resmi oleh kampus, bukan kegiatan keagamaan pribadi.",tambahanMax:0,mkpk:[18,19,20],docs:"Logbook, dokumentasi."},
  {cat:"Kepesertaan",name:"Volunteer Event Terprogram",base:1.0,syarat:"Menyelesaikan tugas sebagai volunteer",tambahanMax:0,mkpk:[18,19],
    coeff:[{label:"Skala kegiatan",key:"skala",options:[{label:"Internasional",value:2},{label:"Nasional",value:1.5},{label:"Regional",value:1.25},{label:"Universitas",value:1},{label:"Fakultas, Prodi, atau Departemen",value:0.75}]}],
    docs:"SK Pimpinan Universitas, Fakultas, atau Prodi, sertifikat, logbook, dokumentasi."},
  {cat:"Kepesertaan",name:"Volunteer Event Insidental",base:0.28,syarat:"Menyelesaikan tugas sebagai volunteer",tambahanMax:0,mkpk:[18,19],
    coeff:[{label:"Skala kegiatan",key:"skala",options:[{label:"Internasional",value:2},{label:"Nasional",value:1.5},{label:"Regional",value:1.25},{label:"Universitas",value:1},{label:"Fakultas, Prodi, atau Departemen",value:0.75}]}],
    docs:"SK Pimpinan Universitas, Fakultas, atau Prodi, sertifikat, logbook, dokumentasi."},
  {cat:"Kepesertaan",name:"Volunteer Berketerampilan Khusus (Terprogram)",base:2.01,syarat:"Menyelesaikan kegiatan volunteer (maks. klaim 2 MKPK)",desc:"Relawan yang memakai keahlian spesifik (medis, teknis, penerjemah, dll.), beda dari relawan acara umum.",tambahanMax:1,
    tambahanOptions:[{label:"Bersertifikat Keahlian",value:1}],
    mkpk:[1,3,6,11,14],docs:"Logbook, dokumentasi, SK atau surat tugas, sertifikat."},
  {cat:"Kepesertaan",name:"Volunteer Berketerampilan Khusus (Insidental)",base:1.07,syarat:"Menyelesaikan kegiatan volunteer (maks. klaim 2 MKPK)",desc:"Sama seperti di atas tapi untuk kegiatan yang sifatnya sewaktu-waktu atau tidak terjadwal rutin.",tambahanMax:1,
    tambahanOptions:[{label:"Bersertifikat Keahlian",value:1}],
    mkpk:[6,14],docs:"Logbook, dokumentasi, SK atau surat tugas, sertifikat."},

  // ================= PENGABDIAN MASYARAKAT =================
  {cat:"Pengabdian Masyarakat",name:"Pemberdayaan Masyarakat Terprogram",base:1.02,syarat:"Menyelesaikan kegiatan pemberdayaan masyarakat terprogram",tambahanMax:5,coeff:[TEAM_ROLE],mkpk:[1,2,6,7,8,13,14],
    tambahanOptions:[
      {label:"Pendanaan ≤10 juta",value:0.5},{label:"Pendanaan 11-50 juta",value:1.5},{label:"Pendanaan >50 juta",value:2},
      {label:"Skala Internal Universitas Hasanuddin",value:1},{label:"Skala Nasional",value:2.5},{label:"Skala Internasional",value:3},
    ],
    tambahanNote:"Ini dua dimensi terpisah (pendanaan dan skala). Pilih maksimal satu dari tiap kelompok, sesuai capaian tertinggi Anda.",
    nilai:[{label:"Ada proposal + laporan atau logbook + publikasi media massa",value:100},{label:"Ada proposal + laporan atau logbook, TANPA publikasi media massa",value:95}],
    docs:"Proposal, laporan kegiatan atau logbook, publikasi media massa (jika ada), SK pendanaan (jika ada)."},
  {cat:"Pengabdian Masyarakat",name:"Bakti Sosial",base:0.24,syarat:"Menyelesaikan kegiatan bakti sosial",tambahanMax:0,mkpk:[2,6],nilai:NILAI_DOKUMEN_90,docs:"Dokumentasi, logbook, laporan, sertifikat atau SK."},
  {cat:"Pengabdian Masyarakat",name:"Kegiatan Kemanusiaan",base:1.33,syarat:"Menyelesaikan kegiatan kemanusiaan (relawan)",tambahanMax:0,mkpk:[6],
    coeff:[{label:"Lama kegiatan",key:"lama",options:[{label:"> 7 hari",value:1.25},{label:"6–7 hari",value:1},{label:"4–5 hari",value:0.75},{label:"1–3 hari",value:0.5}]}],
    nilai:NILAI_DOKUMEN_90,docs:"Surat Tugas atau SK, logbook, dokumentasi, laporan, sertifikat atau SK."},

  // ================= MAGANG atau STUDI INDEPENDEN =================
  {cat:"Magang & Studi Independen",name:"Magang 2 SKS",base:2.0,syarat:"Menyelesaikan kegiatan magang",desc:"Bekerja langsung di perusahaan atau instansi mitra sebagai peserta magang.",tambahanMax:0,mkpk:[21],nilaiWeighted:NILAI_TAHAPAN_MAGANG_SI,docs:"Logbook harian, laporan bulanan, formulir penilaian dosen pembimbing & mitra, laporan akhir & presentasi, SK atau surat penerimaan magang."},
  {cat:"Magang & Studi Independen",name:"Magang 3 SKS",base:3.0,syarat:"Menyelesaikan kegiatan magang",tambahanMax:0,mkpk:[22],nilaiWeighted:NILAI_TAHAPAN_MAGANG_SI,docs:"Logbook harian, laporan bulanan, formulir penilaian dosen pembimbing & mitra, laporan akhir & presentasi, SK atau surat penerimaan magang."},
  {cat:"Magang & Studi Independen",name:"Magang 4 SKS",base:4.0,syarat:"Menyelesaikan kegiatan magang",tambahanMax:0,mkpk:[23],nilaiWeighted:NILAI_TAHAPAN_MAGANG_SI,docs:"Logbook harian, laporan bulanan, formulir penilaian dosen pembimbing & mitra, laporan akhir & presentasi, SK atau surat penerimaan magang."},
  {cat:"Magang & Studi Independen",name:"Magang 6 SKS",base:6.0,syarat:"Menyelesaikan kegiatan magang",tambahanMax:0,mkpk:[24],nilaiWeighted:NILAI_TAHAPAN_MAGANG_SI,docs:"Logbook harian, laporan bulanan, formulir penilaian dosen pembimbing & mitra, laporan akhir & presentasi, SK atau surat penerimaan magang."},
  {cat:"Magang & Studi Independen",name:"Magang 9 SKS",base:9.0,syarat:"Menyelesaikan kegiatan magang",tambahanMax:0,mkpk:[25],nilaiWeighted:NILAI_TAHAPAN_MAGANG_SI,docs:"Logbook harian, laporan bulanan, formulir penilaian dosen pembimbing & mitra, laporan akhir & presentasi, SK atau surat penerimaan magang."},
  {cat:"Magang & Studi Independen",name:"Studi Independen 2 SKS",base:2.0,syarat:"Menyelesaikan kegiatan (bebas status DO evaluasi 4 semester)",desc:"Proyek belajar mandiri dengan bimbingan mentor profesional, biasanya melalui skema Kampus Merdeka (MSIB).",tambahanMax:0,mkpk:[26],nilaiWeighted:NILAI_TAHAPAN_MAGANG_SI,docs:"Laporan pembekalan, logbook atau laporan pelaksanaan, draft tugas atau laporan, logbook konsultasi mentor, laporan akhir."},
  {cat:"Magang & Studi Independen",name:"Studi Independen 4 SKS",base:4.0,syarat:"Menyelesaikan kegiatan (bebas status DO evaluasi 4 semester)",tambahanMax:0,mkpk:[27],nilaiWeighted:NILAI_TAHAPAN_MAGANG_SI,docs:"Bukti konsultasi program, dokumen administrasi atau seleksi, laporan pembekalan, logbook atau laporan pelaksanaan, draft & laporan akhir."},
  {cat:"Magang & Studi Independen",name:"Studi Independen 6 SKS",base:6.0,syarat:"Menyelesaikan kegiatan (bebas status DO evaluasi 4 semester)",tambahanMax:0,mkpk:[28],nilaiWeighted:NILAI_TAHAPAN_MAGANG_SI,docs:"Bukti konsultasi program, dokumen administrasi atau seleksi, laporan pembekalan, logbook atau laporan pelaksanaan, draft & laporan akhir."},

  // ================= PUBLIKASI ILMIAH =================
  {cat:"Publikasi Ilmiah",name:"Artikel Ilmiah",base:4.09,syarat:"Artikel telah diterbitkan pada jurnal nasional atau internasional berbasis riset atau pengabdian",tambahanMax:2,
    tambahanOptions:[{label:"Melaksanakan riset",value:2}],
    mkpk:[2,4,13,15,17,20],
    coeff:[
      {label:"Peran penulis",key:"peran",options:[{label:"Penulis Utama",value:1},{label:"Penulis Pendamping (2–3 penulis, 60%)",value:0.6},{label:"Penulis Pendamping (4–8 penulis, 40%)",value:0.4}]},
      {label:"Jenis jurnal atau skala capaian",key:"jurnal",options:[
        {label:"Jurnal internasional bereputasi (Q1 atau Q2)",value:2},{label:"Jurnal internasional bereputasi (Q3)",value:1.5},
        {label:"Jurnal internasional (Q4 atau belum quartile) atau prosiding internasional bereputasi",value:1.25},{label:"Jurnal nasional riset (SINTA 1–2)",value:1.25},
        {label:"Jurnal internasional & nasional riset (SINTA 3–4)",value:1},{label:"Jurnal internasional & nasional pengabdian masyarakat (SINTA 1–2)",value:0.75},
        {label:"Jurnal nasional riset (SINTA 5–6)",value:0.4},{label:"Jurnal nasional pengabdian masyarakat (SINTA 3–4)",value:0.4},{label:"Jurnal nasional pengabdian masyarakat (SINTA 5–6)",value:0.3},
      ]},
    ],
    docs:"Logbook penyusunan artikel, draft artikel yang didaftarkan ke jurnal, bukti pendaftaran (tangkapan layar sistem jurnal), jawaban atas komentar reviewer, bukti penerimaan, link penerbitan, surat keterangan publikasi PMU Universitas Hasanuddin, tangkapan layar indeksasi Scimago atau SINTA."},

  // ================= MINAT DAN BAKAT =================
  {cat:"Minat & Bakat",name:"Teknologi Tepat Guna",base:1.51,syarat:"Teknologi telah diimplementasikan nyata oleh kelompok masyarakat",desc:"Inovasi teknologi praktis untuk menyelesaikan masalah nyata di masyarakat (mis. alat pertanian, pengolahan limbah).",tambahanMax:1,
    tambahanOptions:[{label:"Memperoleh HKI",value:1}],
    coeff:[TEAM_ROLE],mkpk:[6,8,16],
    nilai:[{label:"Dipakai pemerintah kecamatan atau desa, ≥2 kelompok masyarakat berbeda aktivitas",value:100},{label:"Dipakai oleh 1 kelompok masyarakat",value:90}],
    docs:"Portofolio, desain karya, karya, logbook, laporan, dokumentasi, surat kerja sama (TTD pimpinan prodi atau fakultas), publikasi media."},
  {cat:"Minat & Bakat",name:"Menulis Opini (Media Lokal)",base:0.13,syarat:"Opini telah terbit di media lokal",tambahanMax:0,mkpk:[15],docs:"Bukti terbit (tautan atau kliping media)."},
  {cat:"Minat & Bakat",name:"Menulis Opini (Media Nasional)",base:0.21,syarat:"Opini telah terbit di media nasional",tambahanMax:0,mkpk:[15],docs:"Bukti terbit (tautan atau kliping media)."},
  {cat:"Minat & Bakat",name:"Karya Cipta",base:1.51,syarat:"Karya didaftarkan HKI & diimplementasikan kelompok masyarakat",desc:"Karya orisinal (desain, tulisan, aplikasi, dll.) yang didaftarkan Hak Kekayaan Intelektual (HKI).",tambahanMax:2,
    tambahanOptions:[{label:"Mengikuti kompetisi atau terekam di kanal media digital resmi",value:1},{label:"Mendaftarkan HKI",value:1}],
    coeff:[TEAM_ROLE],mkpk:[14,17,18,19],
    nilai:[{label:"Juara nasional atau terekam di kanal media resmi berbadan hukum (nasional)",value:100},{label:"Juara provinsi atau terekam di kanal media resmi berbadan hukum (provinsi)",value:90}],
    docs:"Portofolio, karya, logbook, laporan, dokumentasi, bukti pendaftaran HKI (Kemenkumham), publikasi media."},
  {cat:"Minat & Bakat",name:"Karya Monumental",base:1.51,syarat:"Karya didaftarkan HKI & diimplementasikan kelompok masyarakat",desc:"Karya berskala besar dengan dampak luas dan diakui publik (mis. instalasi, monumen, proyek besar), didaftarkan HKI.",tambahanMax:2,
    tambahanOptions:[{label:"Mengikuti kompetisi atau terekam di kanal media digital resmi",value:1},{label:"Mendaftarkan HKI",value:1}],
    coeff:[TEAM_ROLE],mkpk:[14,17,18,19],
    nilai:[{label:"Juara nasional atau terekam di kanal media resmi berbadan hukum (nasional)",value:100},{label:"Juara provinsi atau terekam di kanal media resmi berbadan hukum (provinsi)",value:90}],
    docs:"Portofolio, desain karya, karya, logbook, laporan, dokumentasi, publikasi media, bukti pendaftaran HKI."},
  {cat:"Minat & Bakat",name:"Menjadi Duta (Level Universitas)",base:1.13,syarat:"Menyelesaikan tugas sebagai duta level universitas",tambahanMax:0,mkpk:[1,2,5,6,7],docs:"Portofolio, dokumentasi kampanye & seleksi, sertifikat, logbook, SK, jejak digital publikasi."},
  {cat:"Minat & Bakat",name:"Menjadi Duta (Level Provinsi)",base:1.35,syarat:"Menyelesaikan tugas sebagai duta level provinsi",tambahanMax:0,mkpk:[1,2,5,6,7],
    nilai:[{label:"Juara 1, 2, atau 3 tingkat Provinsi",value:90}],
    docs:"Portofolio, dokumentasi kampanye & seleksi, sertifikat, logbook, SK, jejak digital publikasi."},
  {cat:"Minat & Bakat",name:"Menjadi Duta (Level Nasional)",base:2.69,syarat:"Menyelesaikan tugas sebagai duta level nasional",tambahanMax:0,mkpk:[1,2,5,6,7],
    nilai:[{label:"Juara 1, 2, atau 3",value:100},{label:"Juara Harapan",value:95},{label:"Finalis",value:90}],
    docs:"Portofolio, dokumentasi kampanye & seleksi, sertifikat, logbook, SK, jejak digital publikasi."},
  {cat:"Minat & Bakat",name:"Menjadi Duta (Level Regional atau Internasional)",base:3.8,syarat:"Menyelesaikan tugas sebagai duta level regional atau internasional",tambahanMax:0,mkpk:[1,2,5,6,7],
    nilai:[{label:"Finalis hingga Juara 1",value:100}],
    docs:"Portofolio, dokumentasi kampanye & seleksi, sertifikat, logbook, SK, jejak digital publikasi."},
  {cat:"Minat & Bakat",name:"Talent Academy (sebagai Peserta)",base:7.49,syarat:"Menyelesaikan kegiatan Talent Academy sebagai peserta",desc:"Program pembinaan bakat terstruktur yang diselenggarakan universitas, bukan sembarang pelatihan bakat.",tambahanMax:0,mkpk:[4,5,7,11,14,15,18,19,20],
    coeff:[{label:"Tingkat partisipasi",key:"partisipasi",options:[{label:"90–100%",value:1},{label:"80–90%",value:0.75},{label:"70–80%",value:0.5},{label:"60–70%",value:0.25},{label:"< 60%",value:0}]}],
    docs:"Bukti pendaftaran, logbook tiap program, laporan & portofolio, file presentasi & sertifikat."},
  {cat:"Minat & Bakat",name:"Talent Academy (sebagai Fasilitator)",base:0.49,syarat:"Menyelesaikan kegiatan Talent Academy sebagai fasilitator",desc:"Menjadi pembina atau pelatih dalam program Talent Academy resmi kampus.",tambahanMax:0,mkpk:[4,5,7,11,14,15,18,19,20],docs:"Surat penugasan atau sertifikat, laporan penilaian."},
  {cat:"Minat & Bakat",name:"Asisten Praktikum, Laboratorium, atau Peer-Tutor",base:1.66,syarat:"Menyelesaikan tugas sebagai asisten",tambahanMax:0,mkpk:[1,2,6,12,14],
    coeff:[{label:"SKS mata kuliah praktikum",key:"sksmk",options:[{label:"> 3 SKS",value:1.25},{label:"3 SKS",value:1},{label:"2 SKS",value:0.75},{label:"1 SKS",value:0.5}]},{label:"Jumlah praktikan per asisten",key:"praktikan",options:[{label:"> 15 orang",value:1.25},{label:"11–15 orang",value:1},{label:"6–10 orang",value:0.75},{label:"1–5 orang",value:0.5}]}],
    docs:"SK atau surat tugas, logbook, laporan penilaian."},
  {cat:"Minat & Bakat",name:"Asisten Penelitian",base:1.25,syarat:"Menyelesaikan tugas sebagai asisten penelitian",tambahanMax:0,mkpk:[1,2,6,12,14],
    coeff:[{label:"Sumber dana",key:"dana",options:[{label:"Mendapatkan hibah",value:1},{label:"Dana mandiri (maks. 1 mahasiswa)",value:0.25}]}],docs:"SK atau surat tugas, logbook, laporan penilaian."},
  {cat:"Minat & Bakat",name:"Asisten Pengabdian",base:1.07,syarat:"Menyelesaikan tugas sebagai asisten pengabdian",tambahanMax:0,mkpk:[1,2,6,12,14],
    coeff:[{label:"Sumber dana",key:"dana",options:[{label:"Mendapatkan hibah",value:1},{label:"Dana mandiri (maks. 1 mahasiswa)",value:0.25}]}],docs:"SK atau surat tugas, logbook, laporan penilaian."},
  {cat:"Minat & Bakat",name:"Mentor Kompetisi",base:2.0,syarat:"Menyelesaikan tugas sebagai mentor kompetisi",tambahanMax:0,mkpk:[2,11,18,19],docs:"SK Pimpinan Universitas, logbook."},
  {cat:"Minat & Bakat",name:"Mentor Event Terprogram",base:0.56,syarat:"Menyelesaikan tugas sebagai mentor event terprogram",tambahanMax:0,mkpk:[2,11,18,19],docs:"SK Pimpinan Universitas, logbook."},
  {cat:"Minat & Bakat",name:"Mentor MKPK",base:1.02,syarat:"Menyelesaikan tugas sebagai mentor MKPK",desc:"Menjadi pendamping atau mentor bagi mahasiswa lain dalam program MKPK di kampus.",tambahanMax:0,mkpk:[5,14],docs:"SK, dokumentasi, logbook, laporan evaluasi."},
  {cat:"Minat & Bakat",name:"Master of Ceremony",base:0.29,syarat:"Menyelesaikan tugas sebagai MC (event luring, maks. klaim 1 MKPK)",tambahanMax:0,mkpk:[14],
    coeff:[{label:"Skala event",key:"skala",options:[{label:"Internasional",value:2},{label:"Nasional",value:1.5},{label:"Universitas",value:1},{label:"Fakultas, Prodi, atau Departemen",value:0.5}]}],
    docs:"Draft script, surat penetapan sebagai MC dari penyelenggara, logbook & dokumentasi."},
  {cat:"Minat & Bakat",name:"Content Creator",base:1.51,syarat:"Menjadi content creator berbasis edukasi",desc:"Membuat konten edukasi secara rutin di kanal resmi (YouTube, Instagram, dll.), bukan sekadar posting media sosial biasa.",tambahanMax:0,mkpk:[2,5,15,17],docs:"Bukti publikasi konten edukasi, tautan kanal resmi, dokumentasi."},
];

const CATEGORIES = [...new Set(DATA.map(d => d.cat))];

// Default dropdown koefisien atau nilai selalu ke opsi bernilai TERENDAH, bukan yang pertama
// terdaftar di rubrik (yang seringnya justru capaian tertinggi) — supaya orang nggak diam-diam
// kesimpen nilai terlalu tinggi cuma karena lupa ganti dropdown.
function lowestOption(options){
  return options.reduce((min, o) => (o.value < min.value ? o : min), options[0]);
}

function computeSKS(item, coeffValues, tambahan){
  let mult = 1;
  if (item.coeff) for (const g of item.coeff) mult *= coeffValues[g.key] ?? lowestOption(g.options).value;
  return item.base * mult + (Number(tambahan) || 0);
}

// ===========================================================================
// I18N: lapisan terjemahan (chrome antarmuka saja; nama kegiatan atau mata kuliah
// resmi tetap Bahasa Indonesia karena itu istilah asli di rubrik & Sipakamase)
// ===========================================================================
const I18N = {
  id: {
    trustBarText: "Alat independen mahasiswa",
    identifyToggle: "Cara mengenali ini",
    identify1Head: "Bukan bagian dari Universitas Hasanuddin",
    identify1Text: "Dibuat mandiri oleh mahasiswa, berdasarkan Rubrik MKPK Edisi 3. Klaim MKPK yang sesungguhnya tetap melalui Sipakamase.",
    identify2Head: "Data tersimpan lokal di perangkat Anda",
    identify2Text: "Kegiatan yang Anda tambahkan tersimpan di peramban ini saja, tidak dikirim ke mana pun.",
    exportBtn: "Ekspor PDF",
    subtitle: "Setiap kegiatan hanya dapat dikonversi ke mata kuliah MKPK tertentu, sesuai tabel resmi di rubrik. SKS akan dialokasikan secara otomatis ke mata kuliah yang sisa kebutuhannya paling kecil terlebih dahulu, agar semakin banyak mata kuliah yang terpenuhi. Perlu diingat, hasil ini sebatas prediksi. Sebagian mata kuliah membatasi jumlah kegiatan sejenis yang dapat diklaim, jadi tetap periksa syarat lengkapnya di rubrik.",
    statMetLabel: "Mata kuliah terpenuhi",
    statSKSLabel: "SKS terekognisi",
    statSavedLabel: "Kegiatan tersimpan",
    targetLabel: "Target Kelulusan",
    targetKesehatan: "Kesehatan (10 SKS)",
    targetNonKesehatan: "Non-Kesehatan (20 SKS)",
    targetCustom: "Kustom",
    targetDoneTemplate: (done, target) => `${done} / ${target} SKS`,
    targetRemainingShort: (r) => `Kurang ${r} SKS`,
    targetReached: "Target tercapai",
    toastAdded: "Kegiatan berhasil ditambahkan",
    cardAddTitle: "Tambah Kegiatan",
    labelCategory: "Basis",
    labelActivity: "Kategori",
    itemSearchPlaceholder: "Cari atau pilih...",
    comboEmpty: "Tidak ada yang cocok.",
    navAdd: "Tambah Kegiatan",
    navStatus: "Status Mata Kuliah",
    navSaved: "Kegiatan Tersimpan",
    syaratLabel: "Syarat pengakuan",
    labelSpesifik: "Judul Kegiatan Spesifik (opsional)",
    spesifikPlaceholder: 'mis. "Coursera: Data Analysis Specialization", "Juara 2 GEMASTIK Bidang V 2025"',
    spesifikHint: "Diisi supaya daftar kegiatan Anda mudah dibedakan.",
    labelNilai: "Estimasi Nilai",    docsLabel: "Dokumen pendukung yang diperlukan",
    allocTitle: "Alokasi Otomatis ke Mata Kuliah MKPK",
    allocHint: "Mata kuliah yang sudah penuh otomatis dilewati, agar SKS tidak menumpuk di satu tempat saja.",
    allocEmpty: "Semua mata kuliah yang berhak untuk kegiatan ini sudah terpenuhi dari kegiatan lain. Tidak ada tempat lagi untuk mengalokasikan SKS ini.",
    pendingFitTemplate: (n) => `Semua mata kuliah berhak sudah penuh, tapi ada kemungkinan realokasi membuka slot untuk ${n} SKS dari kegiatan ini.`,
    pendingFitViewBtn: "Lihat opsi",
    pendingFitOverlayTitle: "Opsi Realokasi untuk Kegiatan Ini",
    pendingFitSummaryTemplate: (allocated, total) => `Kalau realokasi ini diterapkan, kegiatan yang mau Anda tambahkan bisa dapat ${allocated} dari ${total} SKS.`,
    pendingFitApply: "Terapkan & Tambahkan Kegiatan",
    pendingFitNewActivity: "Kegiatan baru yang mau ditambahkan",
    allocatedLabel: "Teralokasikan",
    resultLabel: "Prediksi total SKS kegiatan ini",
    addBtn: "Tambah ke Daftar",
    cardStatusTitle: "Status per Mata Kuliah MKPK",
    footerRefHead: "Referensi",
    footerCopy: "Dibuat mandiri oleh mahasiswa &middot; Terakhir diperbarui 20 Agustus 2026",
    footerIdentifyBtn: "Cara mengenali alat ini",
    reoptBannerText: (n) => `Sistem menemukan susunan alokasi lebih baik dari kegiatan yang sudah Anda simpan. Berpotensi menyelesaikan ${n} mata kuliah tambahan.`,
    reoptViewDetail: "Lihat Detail",
    reoptOverlayTitle: "Optimasi Alokasi Ditemukan",
    reoptSummaryTemplate: (current, next, names) => `Saat ini ${current} mata kuliah selesai. Dengan alokasi ulang, ${next} mata kuliah bisa selesai, termasuk: ${names}.`,
    reoptChangeArrow: "dialokasikan ulang ke",
    reoptCancel: "Nanti Saja",
    reoptApply: "Terapkan Alokasi Baru",
    reoptAppliedToast: "Alokasi berhasil dioptimasi ulang",
    prDocLabel: "Laporan Prediksi Rekognisi SKS MKPK",
    prTitle: "Prediksi MKPK",
    prSubtitle: "Laporan Prediksi Rekognisi SKS MKPK",
    prPrintedOn: "Dicetak pada",
    prSource: "Sumber: Rubrik MKPK Edisi 3",
    prStatMet: "Mata Kuliah Terpenuhi",
    prStatSKS: "SKS Terekognisi",
    prStatTarget: "Target Kelulusan",
    prCourseStatusTitle: "Status per Mata Kuliah",
    prSavedTitle: "Daftar Kegiatan",
    prColMataKuliah: "Mata Kuliah",
    prColSKS: "SKS",
    prColKebutuhan: "Diperlukan",
    prColStatus: "Status",
    prColKegiatan: "Kegiatan",
    prColTujuan: "Tujuan",
    prColNilai: "Nilai",
    prMet: "Terpenuhi",
    prPending: "Belum",
    prEmptyCourses: "Belum ada mata kuliah yang tersentuh.",
    prEmptySaved: "Belum ada kegiatan tersimpan.",
    prDisclaimer: "Laporan ini alat bantu prediksi mandiri berdasarkan Rubrik MKPK Edisi 3, bukan dokumen resmi Universitas Hasanuddin. Pengisian activity hours dan pengajuan klaim MKPK yang sesungguhnya tetap melalui Sipakamase.",
    guideBtn: "Panduan",
    guideTitle: "Panduan Penggunaan",
    guideSteps: [
      "Pilih kategori dan nama kegiatan yang sesuai dengan yang sudah Anda lakukan.",
      "Isi koefisien, estimasi nilai, dan SKS tambahan sesuai capaian nyata Anda. Sistem akan otomatis menghitung total SKS kegiatan itu.",
      "Sistem otomatis mengisi dulu mata kuliah dengan sisa kebutuhan paling kecil, supaya lebih banyak mata kuliah selesai dan tidak ada penumpukan SKS berlebih di satu mata kuliah saja. Mata kuliah yang sudah penuh otomatis dilewati.",
      "Klik \"Tambah ke Daftar\" untuk menyimpan kegiatan tersebut.",
      "Cek status penyelesaian tiap mata kuliah di bagian \"Status per Mata Kuliah MKPK\".",
      "Pantau progres menuju target kelulusan Anda di bagian atas halaman.",
      "Kalau sistem menemukan susunan alokasi yang lebih baik dari kegiatan-kegiatan yang sudah tersimpan, notifikasi kuning akan muncul. Klik untuk melihat detailnya sebelum diterapkan.",
      "Kalau sudah siap mengajukan klaim yang sesungguhnya, buka tab \"Panduan Konversi Sipakamase\" di bagian atas halaman. Di situ ada urutan langkah persis, supaya hasil di Sipakamase sama dengan prediksi di kalkulator ini.",
      "Ekspor laporan PDF kapan saja melalui tombol \"Ekspor PDF\" di pojok kanan atas.",
    ],
    tambahanLabelTemplate: (max) => `SKS tambahan (maks. ${max} SKS)`,
    tambahanSumTemplate: (sum, max) => `Terpilih: ${sum} dari maksimal ${max} SKS.`,
    tambahanCappedNote: "Kelebihan dari maksimal tidak dihitung.",
    nilaiWeightedResultTemplate: (val) => `Estimasi nilai akhir (dihitung berbobot dari 4 tahap di atas): ${val}`,
    metNoteTemplate: (names) => `Sudah penuh (dilewati): ${names}.`,
    recoLabel: "Rekomendasi Alokasi",
    allocSudah: (already, req) => `${already} / ${req} SKS`,
    allocWastedTemplate: (w) => `${w} SKS tidak terpakai (semua mata kuliah berhak sudah penuh)`,
    emptyCourseSummary: "Belum ada mata kuliah yang tersentuh. Tambahkan kegiatan terlebih dahulu.",
    emptyTable: "Belum ada kegiatan tersimpan.",
    savedTitleTemplate: (n) => `Kegiatan Tersimpan (${n})`,
    courseSubTemplate: (n) => `${n} kegiatan tersambung`,
    badgeMet: (nilai) => `Terpenuhi &middot; Nilai ${nilai}`,
    badgePendingTemplate: (r) => `Kurang ${r} SKS`,
    thKegiatan: "Kegiatan", thMataKuliah: "Mata Kuliah Tujuan", thCakupan: "Cakupan atau Koefisien",
    thSKS: "SKS", thNilai: "Nilai", thDokumen: "Dokumen Diperlukan",
    tambahanExtra: (v) => `+ tambahan ${v} SKS`,
    hapusLabel: "Hapus",
    resetBtn: "Kosongkan",
    resetConfirm: "Hapus semua kegiatan tersimpan? Tindakan ini tidak bisa dibatalkan.",
    resetToast: "Semua kegiatan tersimpan sudah dihapus",
    siteNavCalc: "Kalkulator",
    siteNavGuide: "Panduan Konversi Sipakamase",
    guideLinkBtn: "Cara Konversi ke Sipakamase",
    guidePageDesc: "Sipakamase tidak mengalokasikan SKS secara otomatis. Setiap kegiatan dipilihkan satu mata kuliah secara manual, dan SKS-nya terserap sampai mata kuliah itu penuh, lalu sisanya muncul lagi untuk mata kuliah lain. <strong>Urutan Anda memilih itulah yang menentukan apakah hasilnya sesuai dengan prediksi di halaman ini.</strong> Ikuti langkah-langkah berikut sesuai urutannya.",
    guideEmptyState: "Belum ada kegiatan tersimpan untuk dipandu konversinya. Tambahkan kegiatan terlebih dahulu di tab Kalkulator.",
    guideStepsHeading: "Urutan Konversi",
    guideTotalLabel: "Total",
    guideStepPilih: "Pilih",
    guideStepDoneSingle: (n) => `Seluruh ${n} SKS kegiatan ini langsung terserap di mata kuliah itu. Selesai.`,
    guideStepRemainingNote: (n) => `Sisa ${n} SKS, lanjut ke langkah berikutnya.`,
    guideStepDoneAll: "Sisa 0 SKS, kegiatan ini selesai dikonversi.",
    guideWastedNote: (n) => `Sisa ${n} SKS dari kegiatan ini tidak bisa dikonversi ke mata kuliah manapun (semua mata kuliah yang berhak sudah penuh).`,
    editLabel: "Edit",
    editToast: "Silakan sesuaikan lalu simpan ulang",
    reviewHint: "Cek dulu, jangan asal ikut pilihan default",
    footerTitle: "Prediksi MKPK",
  },
  en: {
    trustBarText: "An independent student tool",
    identifyToggle: "How to recognise this",
    identify1Head: "Not part of Hasanuddin University",
    identify1Text: "Built independently by a student, based on the Rubrik MKPK Edisi 3. Actual MKPK claims are still filed through Sipakamase.",
    identify2Head: "Your data stays on your own device",
    identify2Text: "Activities you add are stored only in this browser, and are never sent anywhere.",
    exportBtn: "Export PDF",
    subtitle: "Each activity can only convert into specific MKPK courses, based on the official mapping table. Credit gets allocated automatically to whichever eligible course needs the least amount first, so more courses end up complete. Just keep in mind this is only a prediction. Some courses cap how many similar activities count, so always double check the details in the rubric.",
    statMetLabel: "Courses completed",
    statSKSLabel: "Credits recognised",
    statSavedLabel: "Activities saved",
    targetLabel: "Graduation Target",
    targetKesehatan: "Health sciences (10 credits)",
    targetNonKesehatan: "Non-health sciences (20 credits)",
    targetCustom: "Custom",
    targetDoneTemplate: (done, target) => `${done} / ${target} credits`,
    targetRemainingShort: (r) => `${r} credits remaining`,
    targetReached: "Target reached",
    toastAdded: "Activity added successfully",
    cardAddTitle: "Add an Activity",
    labelCategory: "Basis",
    labelActivity: "Category",
    itemSearchPlaceholder: "Search or select...",
    comboEmpty: "No matches found.",
    navAdd: "Add Activity",
    navStatus: "Course Status",
    navSaved: "Saved Activities",
    syaratLabel: "Recognition requirement",
    labelSpesifik: "Specific Activity Title (optional)",
    spesifikPlaceholder: 'e.g. "Coursera: Data Analysis Specialization", "2nd Place, GEMASTIK Category V 2025"',
    spesifikHint: "This helps you tell your saved activities apart.",
    labelNilai: "Estimated Grade",    docsLabel: "Supporting documents required",
    allocTitle: "Automatic Allocation to MKPK Courses",
    allocHint: "Courses that are already full are skipped automatically, so credit doesn't pile up in just one place.",
    allocEmpty: "Every course this activity is eligible for has already been completed by other activities. There's nowhere left to allocate this credit.",
    pendingFitTemplate: (n) => `Every eligible course is already full, but reallocating existing entries could open up ${n} credits for this activity.`,
    pendingFitViewBtn: "View options",
    pendingFitOverlayTitle: "Reallocation Options for This Activity",
    pendingFitSummaryTemplate: (allocated, total) => `If this reallocation is applied, the activity you're adding could receive ${allocated} of ${total} credits.`,
    pendingFitApply: "Apply & Add Activity",
    pendingFitNewActivity: "The new activity you're adding",
    allocatedLabel: "Allocated",
    resultLabel: "Predicted total credit for this activity",
    addBtn: "Add to List",
    cardStatusTitle: "Status by MKPK Course",
    footerRefHead: "Reference",
    footerCopy: "Built independently by a student &middot; Last updated 20 August 2026",
    footerIdentifyBtn: "How to recognise this tool",
    reoptBannerText: (n) => `The system found a better allocation across the activities you've already saved. Could complete ${n} more course${n === 1 ? '' : 's'}.`,
    reoptViewDetail: "View Details",
    reoptOverlayTitle: "Allocation Optimisation Found",
    reoptSummaryTemplate: (current, next, names) => `Currently ${current} course${current === 1 ? '' : 's'} complete. Reallocating could complete ${next}, including: ${names}.`,
    reoptChangeArrow: "reallocated to",
    reoptCancel: "Not Now",
    reoptApply: "Apply New Allocation",
    reoptAppliedToast: "Allocation successfully re-optimised",
    prDocLabel: "MKPK Credit Recognition Prediction Report",
    prTitle: "Prediksi MKPK",
    prSubtitle: "MKPK Credit Recognition Prediction Report",
    prPrintedOn: "Printed on",
    prSource: "Source: Rubrik MKPK Edisi 3",
    prStatMet: "Courses Completed",
    prStatSKS: "Credits Recognised",
    prStatTarget: "Graduation Target",
    prCourseStatusTitle: "Status by Course",
    prSavedTitle: "Activity List",
    prColMataKuliah: "Course",
    prColSKS: "Credits",
    prColKebutuhan: "Required",
    prColStatus: "Status",
    prColKegiatan: "Activity",
    prColTujuan: "Target",
    prColNilai: "Grade",
    prMet: "Complete",
    prPending: "Pending",
    prEmptyCourses: "No courses touched yet.",
    prEmptySaved: "No activities saved yet.",
    prDisclaimer: "This report is an independent prediction tool based on the Rubrik MKPK Edisi 3, not an official Universitas Hasanuddin document. Logging activity hours and filing an actual MKPK claim is still done through Sipakamase.",
    guideBtn: "Guide",
    guideTitle: "How to Use This Tool",
    guideSteps: [
      "Choose the category and activity name that matches what you actually did.",
      "Fill in the coefficient, estimated grade, and additional credit based on your real achievement. The system will work out the total credit automatically.",
      "The system fills whichever eligible course has the smallest remaining requirement first, so more courses get completed and credit isn't overstacked into a single course. Courses that are already full are skipped automatically.",
      "Click \"Add to List\" to save the activity.",
      "Check each course's completion status under \"Status by MKPK Course\".",
      "Track your progress towards your graduation target near the top of the page.",
      "If the system finds a better allocation across your saved activities, a yellow notification appears. Click it to review the details before applying.",
      "When you're ready to file the real claim, open the \"Sipakamase Conversion Guide\" tab near the top of the page. It walks through the exact order needed so the outcome in Sipakamase matches this calculator's prediction.",
      "Export a PDF report at any time using the \"Export PDF\" button in the top right.",
    ],
    tambahanLabelTemplate: (max) => `Additional credit (max. ${max} credits)`,
    tambahanSumTemplate: (sum, max) => `Selected: ${sum} out of a maximum ${max} credits.`,
    tambahanCappedNote: "Anything above the maximum isn't counted.",
    nilaiWeightedResultTemplate: (val) => `Final estimated grade (weighted across the 4 stages above): ${val}`,
    metNoteTemplate: (names) => `Already complete (skipped): ${names}.`,
    recoLabel: "Allocation Recommendation",
    allocSudah: (already, req) => `${already} / ${req} credits`,
    allocWastedTemplate: (w) => `${w} credits unused (every eligible course is already complete)`,
    emptyCourseSummary: "No courses touched yet. Add an activity above first.",
    emptyTable: "No activities saved yet.",
    savedTitleTemplate: (n) => `Saved Activities (${n})`,
    courseSubTemplate: (n) => `${n} activit${n === 1 ? "y" : "ies"} linked`,
    badgeMet: (nilai) => `Complete &middot; Grade ${nilai}`,
    badgePendingTemplate: (r) => `${r} credits short`,
    thKegiatan: "Activity", thMataKuliah: "Target Course", thCakupan: "Scope/Coefficient",
    thSKS: "Credits", thNilai: "Grade", thDokumen: "Documents Required",
    tambahanExtra: (v) => `+ ${v} additional credits`,
    hapusLabel: "Remove",
    resetBtn: "Clear all",
    resetConfirm: "Delete all saved activities? This cannot be undone.",
    resetToast: "All saved activities have been cleared",
    siteNavCalc: "Calculator",
    siteNavGuide: "Sipakamase Conversion Guide",
    guideLinkBtn: "How to Convert in Sipakamase",
    guidePageDesc: "Sipakamase does not allocate credit automatically. Each activity is manually assigned to one course, and the credit is absorbed until that course is full, then the remainder reappears for another course. <strong>This selection order is what determines whether the result matches the prediction on this page.</strong> Follow the steps below in the order shown.",
    guideEmptyState: "No saved activities to guide the conversion for yet. Please add activities in the Calculator tab first.",
    guideStepsHeading: "Conversion Order",
    guideTotalLabel: "Total",
    guideStepPilih: "Select",
    guideStepDoneSingle: (n) => `All ${n} credits from this activity go straight into that course. Done.`,
    guideStepRemainingNote: (n) => `${n} credits remain, continue to the next step.`,
    guideStepDoneAll: "0 credits remaining, this activity is fully converted.",
    guideWastedNote: (n) => `${n} credits from this activity can't be converted into any course (every eligible course is already full).`,
    editLabel: "Edit",
    editToast: "Adjust the details, then save again",
    reviewHint: "Double-check this, don't just leave the default",
    footerTitle: "Prediksi MKPK",
  },
};
